import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Printer, FileText, User, Activity, AlertCircle } from 'lucide-react';
import { getScanById } from '../utils/storage';
import './ReportPage.css';

export default function ReportPage() {
  const { caseId } = useParams();
  const navigate = useNavigate();
  const [scanData, setScanData] = useState(null);

  useEffect(() => {
    let isMounted = true;
    const fetchScan = async () => {
      const data = await getScanById(caseId);
      if (isMounted && data) {
        setScanData(data);
      }
    };
    fetchScan();
    return () => { isMounted = false; };
  }, [caseId]);

  if (!scanData) {
    return (
      <div className="report-page animate-fade-in" style={{ textAlign: 'center', padding: '4rem' }}>
        <h2>Report Not Found</h2>
        <p style={{ color: 'var(--color-text-muted)', marginBottom: '2rem' }}>No analysis results found for {caseId}</p>
        <button className="btn-primary" onClick={() => navigate(-1)}>Go Back</button>
      </div>
    );
  }

  const { score, abnormalCount, regions } = scanData;
  const abnormalRegionNames = regions.filter(r => r.status === 'abnormal').map(r => r.name).join(', ');

  return (
    <div className="report-page animate-fade-in">
      <div className="report-header">
        <div className="report-header-left">
          <button className="back-btn" onClick={() => navigate(-1)} style={{ padding: 0, width: 'fit-content' }}>
            <ArrowLeft size={20} /> Back to Analysis
          </button>
          <div className="report-title-section">
            <h1>Detailed Analysis Report</h1>
            <p className="report-subtitle">Generated by Ischemic</p>
          </div>
        </div>
        <button className="print-btn" onClick={() => window.print()}>
          <Printer size={18} /> Print Report
        </button>
      </div>

      <div className="report-section glass-card">
        <h2 className="section-title"><User size={20} /> Case Information</h2>
        <div className="patient-info-grid">
          <div className="info-item">
            <span className="info-label">CASE ID</span>
            <span className="info-value">{caseId}</span>
          </div>
          <div className="info-item">
            <span className="info-label">MODALITY</span>
            <span className="info-value">Non-Contrast CT (NCCT)</span>
          </div>
          <div className="info-item">
            <span className="info-label">SLICE THICKNESS</span>
            <span className="info-value">5mm</span>
          </div>
          <div className="info-item">
            <span className="info-label">STUDY DATE</span>
            <span className="info-value">{new Date(scanData.date || Date.now()).toLocaleDateString()}</span>
          </div>
        </div>
      </div>

      <div className="report-section glass-card">
        <h2 className="section-title"><Activity size={20} /> Analysis Summary</h2>
        
        <div className="score-highlight">
          <div className="score-display">
            {score} <span className="score-max">/ 10</span>
          </div>
          <div className="score-text">
            <p style={{ fontSize: '1.1rem', marginBottom: '0.25rem' }}>ASPECTS Score calculated automatically.</p>
            <p style={{ color: 'var(--color-text-muted)' }}>{abnormalCount} of 10 regions show signs of early ischemic change.</p>
          </div>
        </div>
        
        <div style={{ marginTop: '1rem' }}>
          <h3 style={{ fontSize: '1rem', marginBottom: '0.5rem', color: 'var(--color-mint-light)' }}>Affected Regions</h3>
          <p>{abnormalCount > 0 ? abnormalRegionNames : 'None detected'}</p>
        </div>
      </div>

      <div className="report-section glass-card">
        <h2 className="section-title"><FileText size={20} /> Region-Level Findings</h2>
        
        <table className="regions-table">
          <thead>
            <tr>
              <th>REGION</th>
              <th>FINDING</th>
            </tr>
          </thead>
          <tbody>
            {regions.map((region, idx) => (
              <tr key={idx}>
                <td style={{ fontWeight: 500 }}>{region.name}</td>
                <td>
                  <span className={`status-badge ${region.status}`}>
                    {region.status === 'abnormal' ? 'Ischemic Change Detected' : 'Normal'}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div style={{ padding: '1rem', background: 'rgba(220, 53, 69, 0.05)', border: '1px solid rgba(220, 53, 69, 0.2)', borderRadius: '8px', display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
        <AlertCircle size={24} color="#dc3545" style={{ flexShrink: 0 }} />
        <p style={{ fontSize: '0.85rem', color: 'var(--color-text-muted)', lineHeight: 1.5 }}>
          <strong>Clinical Disclaimer:</strong> This automated report is generated by an investigational AI tool intended for research and demonstration purposes only. It is not FDA-approved for clinical diagnostic use. The ASPECTS score provided here should not be used as the sole basis for clinical decisions. All findings must be independently verified by a qualified radiologist or neurologist.
        </p>
      </div>
    </div>
  );
}
